In [1]:
from collections import defaultdict
import math
import pandas as pd
import re
from datetime import datetime 
import numpy as np
from decimal import Decimal
import matplotlib.pyplot as plt
import pylab

print('numpy: ',np.version.version)
print('pandas: ',pd.__version__)
languages = ['en', 'es', 'eu', 'ca', 'pt', 'gl']

numpy:  1.17.2
pandas:  1.0.3


In [2]:
df = pd.read_csv('../OriginalDataSet/training-tweets.txt', encoding='utf-8', error_bad_lines=False, sep='\t', nrows=18000)
df.columns = ['TweetID', 'UserID', 'Language', "Tweet"]

b'Skipping line 17: expected 4 fields, saw 5\nSkipping line 33: expected 4 fields, saw 5\nSkipping line 44: expected 4 fields, saw 5\nSkipping line 58: expected 4 fields, saw 5\nSkipping line 61: expected 4 fields, saw 5\nSkipping line 64: expected 4 fields, saw 5\nSkipping line 74: expected 4 fields, saw 5\nSkipping line 91: expected 4 fields, saw 5\nSkipping line 99: expected 4 fields, saw 5\nSkipping line 140: expected 4 fields, saw 5\nSkipping line 145: expected 4 fields, saw 5\nSkipping line 148: expected 4 fields, saw 5\nSkipping line 152: expected 4 fields, saw 5\nSkipping line 171: expected 4 fields, saw 5\nSkipping line 178: expected 4 fields, saw 5\nSkipping line 197: expected 4 fields, saw 5\nSkipping line 201: expected 4 fields, saw 5\nSkipping line 203: expected 4 fields, saw 5\nSkipping line 213: expected 4 fields, saw 5\nSkipping line 216: expected 4 fields, saw 5\n'


In [3]:
_df0 = df[['Language', 'Tweet']].copy()
pattern = re.compile('[ ]')
# _df0.head()

for language in languages:
    exec("%sAlphabets={}" % (language))
    exec ('{0}Size = 0'.format(language))

In [4]:
start_time = datetime.now() 
trainDict = defaultdict(list)
for index, row in _df0.iterrows():
    sentence = ''
    tweet = row['Tweet']
    language = row['Language']
    for letter in tweet:
        if letter.isalpha() or pattern.match(letter):
            exec('if \'{let}\' not in {lang}Alphabets.keys():\n\
                     {lang}Alphabets[letter] = {lang}Size\n\
                     {lang}Size += 1'.format(let=letter, lang=language))#, language, language, language))
            sentence = sentence + letter
    trainDict[row['Language']].append(sentence)
print('Reading time (hh:mm:ss.ms) {}'.format(datetime.now() - start_time ))

Reading time (hh:mm:ss.ms) 0:00:28.487350


In [18]:
for language in languages:
    exec('{lang}Model=np.zeros(shape=(({lang}Size+1),({lang}Size+1),({lang}Size+1)))'.format(lang=language))#, language, language, language))

#### For Bigrams

In [ ]:
# start_time = datetime.now()
# delta = 0.5
# for language, tweets in trainDict.items():
#     for tweet in tweets:
#         for i in range(len(tweet)-2):
#             first = tweet[i]
#             second = tweet[i+1]
#             exec('firstIndex = %sAlphabets[first]'%(language))
#             exec('secondIndex = %sAlphabets[second]'%(language))
#             exec('%sModel[firstIndex][secondIndex] += 1'%(language))
# for language in languages:
#     exec('%sModel = np.add(%sModel, delta)'%(language, language)) #this is where smoothing happens
#     exec('%sModelFinal = %sModel/%sModel.sum(axis=1)'%(language, language, language)) #divide all the values by the sum of the row
#     exec('%sModelFinal = np.log10(%sModelFinal)'%(language, language))
# print('Training time (hh:mm:ss.ms) {}'.format(datetime.now() - start_time ))

In [19]:
print(enAlphabets)
print('EN',enModel, enModel.shape)
print(trainDict)

{'I': 0, 'M': 1, ' ': 2, 'C': 3, 'O': 4, 'N': 5, 'F': 6, 'U': 7, 'S': 8, 'E': 9, 'D': 10, 'W': 11, 'H': 12, 'A': 13, 'T': 14, 'R': 15, 'L': 16, 'J': 17, 'j': 18, 'u': 19, 's': 20, 't': 21, 'i': 22, 'n': 23, 'b': 24, 'e': 25, 'r': 26, 'a': 27, 'f': 28, 'o': 29, 'd': 30, 'y': 31, 'p': 32, 'h': 33, 'P': 34, 'm': 35, 'l': 36, 'c': 37, 'Q': 38, 'Z': 39, 'B': 40, 'z': 41, 'v': 42, 'g': 43, 'k': 44, 'w': 45, 'Y': 46, 'x': 47, 'K': 48, 'V': 49, 'X': 50, 'q': 51, 'G': 52, 'á': 53, 'ñ': 54, 'Ú': 55, 'í': 56, 'è': 57, 'ó': 58, 'ü': 59, 'é': 60, 'ç': 61, 'ã': 62, 'à': 63, 'ā': 64, 'ò': 65, 'б': 66, 'а': 67, 'р': 68, 'с': 69, 'е': 70, 'л': 71, 'о': 72, 'н': 73, 'É': 74, 'º': 75, 'Ó': 76}
EN [[[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. .

In [ ]:
# trainDict = {'en': ['this is a boy']}
# enModel[24][29][31]

#### For Trigrams

In [20]:
start_time = datetime.now()
delta = 0.5
for language, tweets in trainDict.items():
    for tweet in tweets:
        for i in range(len(tweet)-2):
            first = tweet[i]
            second = tweet[i+1]
            third = tweet[i+2]
            exec('firstIndex = %sAlphabets[first]'%(language))
            exec('secondIndex = %sAlphabets[second]'%(language))
            exec('thirdIndex = %sAlphabets[third]'%(language))
            exec('%sModel[firstIndex][secondIndex][thirdIndex] += 1'%(language))
            
for language in languages:
    exec('for x in range({lang}Model.shape[0]):\n\
    for y in range({lang}Model.shape[0]):\n\
        sumCol = 0\n\
        for z in range({lang}Model.shape[0]):\n\
            {lang}Model[x][y][z] += delta\n\
            sumCol += {lang}Model[x][y][z]\n\
        for z in range({lang}Model.shape[0]):\n\
            {lang}Model[x][y][z] /= sumCol\n\
                \n\
{lang}Model = np.log10({lang}Model)'.format(lang=language))

print('Training time (hh:mm:ss.ms) {}'.format(datetime.now() - start_time ))

Training time (hh:mm:ss.ms) 0:01:05.798111


In [21]:
print(enModel)

[[[-1.91381385 -1.91381385 -1.4366926  ... -1.91381385 -1.91381385
   -1.91381385]
  [-1.53991208 -2.01703334 -0.90308999 ... -2.01703334 -2.01703334
   -2.01703334]
  [-2.62531245 -1.78021441 -1.78021441 ... -2.62531245 -2.62531245
   -2.62531245]
  ...
  [-1.8920946  -1.8920946  -1.8920946  ... -1.8920946  -1.8920946
   -1.8920946 ]
  [-1.90308999 -1.90308999 -1.90308999 ... -1.90308999 -1.90308999
   -1.90308999]
  [-1.8920946  -1.8920946  -1.8920946  ... -1.8920946  -1.8920946
   -1.8920946 ]]

 [[-1.94448267 -1.94448267 -1.94448267 ... -1.94448267 -1.94448267
   -1.94448267]
  [-1.91381385 -1.91381385 -1.21484385 ... -1.91381385 -1.91381385
   -1.91381385]
  [-1.57209677 -2.04921802 -1.57209677 ... -2.04921802 -2.04921802
   -2.04921802]
  ...
  [-1.8920946  -1.8920946  -1.8920946  ... -1.8920946  -1.8920946
   -1.8920946 ]
  [-1.8920946  -1.8920946  -1.8920946  ... -1.8920946  -1.8920946
   -1.8920946 ]
  [-1.8920946  -1.8920946  -1.8920946  ... -1.8920946  -1.8920946
   -1.89209

## Testing the models

In [22]:
df = pd.read_csv('../OriginalDataSet/test-tweets-given.txt', encoding='utf-8', error_bad_lines=False, sep='\t', nrows=100)
df.columns = ['TweetID', 'UserID', 'Language', "Tweet"]
_df0 = df[['TweetID', 'Language', 'Tweet']].copy()
# pattern = re.compile('[a-z ]')
# _df0.head()

In [23]:
probability = {}
for index, row in _df0.iterrows():
    for language in languages:
        exec("%sProb=math.log10(1/6)" % (language))
    tweetID = row['TweetID']
    langTweet = row['Language']
    tweet = row['Tweet']
    
    for i in range(len(tweet)-2):
        first = tweet[i]
        second = tweet[i+1]
        third = tweet[i+2]
        for language in languages:
            exec('if ((first not in {lang}Alphabets.keys()) and (second not in {lang}Alphabets.keys()) and (third not in {lang}Alphabets.keys())):\n\
    prob = {lang}Model[-1][-1][-1]\n\
elif ( (first not in {lang}Alphabets.keys()) and (second not in {lang}Alphabets.keys()) ):\n\
    index = {lang}Alphabets[third]\n\
    prob = {lang}Model[-1][-1][index]\n\
elif ( (first not in {lang}Alphabets.keys()) and (third not in {lang}Alphabets.keys()) ):\n\
    index = {lang}Alphabets[second]\n\
    prob = {lang}Model[-1][index][-1]\n\
elif ( (second not in {lang}Alphabets.keys()) and (third not in {lang}Alphabets.keys()) ):\n\
    index = {lang}Alphabets[first]\n\
    prob = {lang}Model[index][-1][-1]\n\
elif first not in {lang}Alphabets.keys():\n\
    secondIndex = {lang}Alphabets[second]\n\
    thirdIndex = {lang}Alphabets[third]\n\
    prob = {lang}Model[-1][secondIndex][thirdIndex]\n\
elif second not in {lang}Alphabets.keys():\n\
    firstIndex = {lang}Alphabets[first]\n\
    thirdIndex = {lang}Alphabets[third]\n\
    prob = {lang}Model[firstIndex][-1][thirdIndex]\n\
elif third not in {lang}Alphabets.keys():\n\
    firstIndex = {lang}Alphabets[first]\n\
    secondIndex = {lang}Alphabets[second]\n\
    prob = {lang}Model[firstIndex][secondIndex][-1]\n\
else:\n\
    firstIndex = {lang}Alphabets[first]\n\
    secondIndex = {lang}Alphabets[second]\n\
    thirdIndex = {lang}Alphabets[third]\n\
    prob = {lang}Model[firstIndex][secondIndex][thirdIndex]\n\
{lang}Prob = prob + {lang}Prob\n'.format(lang='en'))
    for langu in languages:
        exec("probability['%s'] = %sProb"%(langu, langu))
    result = max(probability, key=probability.get)
    print(tweetID, '  ', result, '  ', '%.2E' % Decimal(probability[result]), '  ', langTweet, 'correct' if (langTweet==result) else 'wrong')

439381946939232257    es    -7.78E-01    es correct
439389330533273600    es    -7.78E-01    es correct
439392779786285056    es    -7.78E-01    es correct
439393603845373952    es    -7.78E-01    es correct
439395306464346112    es    -7.78E-01    eu wrong
439403680245493760    es    -7.78E-01    es correct
439407703358967808    es    -7.78E-01    es correct
439408603167211520    es    -7.78E-01    es correct
439410377286492160    es    -7.78E-01    es correct
439411327971643392    es    -7.78E-01    es correct
439414230413217792    es    -7.78E-01    es correct
439415113045778432    es    -7.78E-01    eu wrong
439420783698640896    es    -7.78E-01    es correct
439428207222484992    es    -7.78E-01    es correct
439435803983634432    es    -7.78E-01    es correct
439437804352057344    es    -7.78E-01    es correct
439438406117232640    es    -7.78E-01    es correct
439449097658195968    es    -7.78E-01    es correct
439455534304210944    es    -7.78E-01    eu wrong
439460634212970496

0
1
2
1
2
3
2
3
4
last: a


# Important Stuff

In [ ]:
B = np.arange(27.0).reshape((3,3,3))
print(B)
B[0][0][0] = 0
B[0][0][1] = 0
B[0][0][2] = 0
for x in range(B.shape[0]):
    for y in range(B.shape[0]):
        sumCol = 0
        for z in range(B.shape[0]):
            sumCol = sumCol + B[x][y][z]
#         print('sum for [%d][%d]'%(x,y), sumCol)
        if sumCol != 0:
            for z in range(B.shape[0]):
                B[x][y][z] /= sumCol
print(B)

In [16]:
lang = 'en'
str = 'for x in range({lang}Model.shape[0]):\n\
    for y in range({lang}Model.shape[0]):\n\
        sumCol = 0\n\
        for z in range({lang}Model.shape[0]):\n\
            {lang}Model[x][y][z] += delta\n\
            sumCol += {lang}Model[x][y][z]\n\
        for z in range({lang}Model.shape[0]):\n\
            {lang}Model[x][y][z] /= sumCol\n\
                \n\
{lang}Model = np.log10({lang}Model)'.format(lang=language)
print(str)

for x in range(glModel.shape[0]):
    for y in range(glModel.shape[0]):
        sumCol = 0
        for z in range(glModel.shape[0]):
            glModel[x][y][z] += delta
            sumCol += glModel[x][y][z]
        for z in range(glModel.shape[0]):
            glModel[x][y][z] /= sumCol
                
glModel = np.log10(glModel)


In [ ]:
lang = 'en'
str = 'if ((first not in {lang}Alphabets.keys()) and (second not in {lang}Alphabets.keys()) and (third not in {lang}Alphabets.keys())):\n\
    prob = {lang}Model[-1][-1][-1]\n\
elif ( (first not in {lang}Alphabets.keys()) and (second not in {lang}Alphabets.keys()) ):\n\
    index = {lang}Alphabets[third]\n\
    prob = {lang}Model[-1][-1][index]\n\
elif ( (first not in {lang}Alphabets.keys()) and (third not in {lang}Alphabets.keys()) ):\n\
    index = {lang}Alphabets[second]\n\
    prob = {lang}Model[-1][index][-1]\n\
elif ( (second not in {lang}Alphabets.keys()) and (third not in {lang}Alphabets.keys()) ):\n\
    index = {lang}Alphabets[first]\n\
    prob = {lang}Model[index][-1][-1]\n\
elif first not in {lang}Alphabets.keys():\n\
    secondIndex = {lang}Alphabets[second]\n\
    thirdIndex = {lang}Alphabets[third]\n\
    prob = {lang}Model[-1][secondIndex][thirdIndex]\n\
elif second not in {lang}Alphabets.keys():\n\
    firstIndex = {lang}Alphabets[first]\n\
    thirdIndex = {lang}Alphabets[third]\n\
    prob = {lang}Model[firstIndex][-1][thirdIndex]\n\
elif third not in {lang}Alphabets.keys():\n\
    firstIndex = {lang}Alphabets[first]\n\
    secondIndex = {lang}Alphabets[second]\n\
    prob = {lang}Model[firstIndex][secondIndex][-1]\n\
else:\n\
    firstIndex = {lang}Alphabets[first]\n\
    secondIndex = {lang}Alphabets[second]\n\
    thirdIndex = {lang}Alphabets[third]\n\
    prob = {lang}Model[firstIndex][secondIndex][thirdIndex]\n\
{lang}Prob = prob + {lang}Prob\n'.format(lang='en')
    
print(str)